# this script fetches and cleans the data
# note that qualtrics credentials for the API are needed

library(qualtRics)
library(tidyverse)
library(lubridate)
library(labelled)

#browse all surveys
surveys <- all_surveys()
surveys

#we want data from the 5th one in the list ( among my list of surveys)
df <- fetch_survey(surveys$id[5], label = FALSE, convert = FALSE, force_request = TRUE)


dup_ip <- df %>% 
  select(IPAddress) %>% 
  group_by(IPAddress) %>% 
  filter(n() > 1) 

dup_ip <- dup_ip$IPAddress

#lets remove"项" from the treatment, control and placebo groups
#keep_digit <- function(x) gsub("[^0-9]", "", x)
#
#vars <- c("a_control", "a_treatment", "b_control", "b_placebo", "b_treatment",
#          "c_control", "c_treatment", "d_control","d_treatment",
#          "e_control", "e_placebo", "e_treatment")
#
#df <-  df %>% mutate_at(vars, keep_digit) %>% 
#  mutate_at(vars, as.numeric)

df <- df %>% 
  filter(date(StartDate) > date("2019-10-26")) %>% # removes the 156 autogenerated test obs
  mutate(round = ifelse(date(StartDate) == "2019-10-28", "pilot_1", 
                        ifelse(date(StartDate) == "2019-10-30", "pilot_2",
                               ifelse(date(StartDate) == "2019-11-01", "pilot_3", 
                                      "full_launch"))),
         time_spent = time_length(interval(as_datetime(StartDate), as_datetime(EndDate))), 
         speeder = ifelse(time_spent < 90, "yes", "no"), 
         duplicated_ip = ifelse(IPAddress %in% dup_ip, "yes", "no"), #there some 500 duplicated, among which 130 ish are unique
         imc_2_1_pass = ifelse(imc_2_1 == 3, 1, 0),
         imc_2_2_pass = ifelse(imc_2_2 == 5, 1, 0),
         imc_1_pass = ifelse(IMC_1_4 == 1 & IMC_1_6 == 1, 1, 0),
         imc_1_pass = ifelse(is.na(imc_1_pass), 0, imc_1_pass),
         attentive = ifelse(imc_2_1_pass == 1 & imc_2_2_pass == 1, 1, 0), 
         very_attentive = ifelse(attentive == 1 & imc_1_pass == 1, 1, 0),
         data_quality = ifelse(very_attentive == 1, "good",
                               ifelse(attentive == 1, "ok", "bad")),
         unique_ip = ifelse(duplicated(IPAddress) == FALSE, 1, 0), 
         using = ifelse(round == "full_launch" & Finished == 1 & unique_ip == 1, "yes", "no"), 
         audit_recieved = ifelse(is.na(audit), 0, 1),
         audit_pass = ifelse(audit_recieved == 1 & audit == 1, 1, 0),
         fmc_a = ifelse(fmc_a == 1, 1, 0),
         fmc_b = ifelse(fmc_b == 1, 1, 0),
         fmc_e = ifelse(fmc_e == 1, 1, 0),
         c_direct_dk = ifelse(c_direct == 3, 1, 0), #for priming checks
         d_direct_dk = ifelse(d_direct == 3, 1, 0), #and filter drop DK
         e_direct_dk = ifelse(e_direct == 3, 1, 0), #in main analysis
         c_direct = ifelse(c_direct == 1, 1, 0), 
         d_direct = ifelse(d_direct == 1, 1, 0), 
         e_direct = ifelse(e_direct == 1, 1, 0),
         placebo_direct = ifelse(placebo_1_direct == 1 | placebo_2_direct == 1, 1, 0), 
         party_member = ifelse(party==1,1,0), 
         female = ifelse(gender==2,1,0), 
         urban_hukou = ifelse(hukou==1,1,0), 
         income = ifelse(income == 7, NA, 
                         ifelse(income == 8, 5, 
                                ifelse(income == 5, 6, 
                                       ifelse(income==6, 7, income)))), 
         education = ifelse(education == 8, NA, education),
         work = dplyr::recode(work, `1`= "government", `2`= "private sector",`3`= "NGO", `4`="Other", `5`= "DK"),
         work_gov = ifelse(work == "government", 1, 0),
         lng = LocationLongitude, 
         lat = LocationLatitude, 
         block_a_before_b = ifelse(`RO-BR-FL_71` == "FL_72|FL_73", 1, 0), 
         block_c_before_d = ifelse(`RO-BR-FL_77` == "FL_74|FL_44", 1, 0), 
         sponsor_gov = ifelse(sponsor==1, 1, ifelse(sponsor==7, NA, 0))
         ) 
         
subtract <- function(x) x - 1

vars <- c("a_control", "a_treatment", "b_control", "b_placebo", "b_treatment",
          "c_control", "c_treatment", "d_control","d_treatment",
          "e_control", "e_placebo", "e_treatment")

df <-  df %>% mutate_at(vars, subtract) 


#to lucid
#df %>%
#  select(ResponseID, rid, round, speeder, duplicated_ip, data_quality, using) %>% 
#  write_csv(, "data/china_survey.csv")
         
  
# lets write this data in the data folder note we both have to run this 
# script to have tha data localy as i put "survey-data.csv" in the .gitignore 

df %>% 
  select(vars, age, income:work, audit, fmc_a, fmc_b, fmc_e, c_direct, 
         d_direct, e_direct, round:sponsor_gov) %>% 
  remove_labels() %>% 
  write_csv(., "data/survey-data.csv")



# lets get the survey questions
questions <- survey_questions(surveys$id[7]) #to get the english version
questions

# need to clean away html-junk...
#lets write a cleaner function
clean_html <- function(x) {
  return(gsub("<.*?>", "", x))
}

#seem to work
questions <- questions %>% 
  mutate(Wording = clean_html(question), 
         Tag = clean_html(qname)) %>%
  select(Tag, Wording) %>% 
  distinct(Tag, .keep_all = TRUE)


# save as csv to be called from pap2.Rmd
write_csv(questions, "data/question_wording.csv")





